name: ResUNet
channels:
  - default
  - conda-forge
dependencies:
  - pytorch
  - pillow=9.1.0
  - numpy=1.22.4
  - scikit-learn=1.0.2
  - matplotlib
  - seaborn
  - opencv=4.5.5
  - pandas=1.4.1
  - torchvision
  - gdal
  - openpyxl
  - tensorboard=2.11.0